### ISSUE TITLE
prepare_crush_check exception for osd.2^31-1

### ISSUE THREAD

**Issue by stuartthebruce** [TheJJ/ceph-balancer#12]
It might be worth better handling of osd = 2^31-1 (aka NONE) when there is a missing osd in a pg,
```
[root@ceph-admin ~]# ./placementoptimizer.py -v balance --max-pg-moves 10 --max-full-move-attempts=100 | tee /tmp/balance-upmaps
[2022-06-27 15:09:30,803] gathering cluster state via ceph api...
[2022-06-27 15:10:05,578] running pg balancer
[2022-06-27 15:10:05,865] current OSD fill rate per crushclasses:
[2022-06-27 15:10:05,865]   mddu: average=0.21%, median=0.21%, without_placement_constraints=1.16%
[2022-06-27 15:10:05,866]   mddm: average=0.16%, median=0.16%, without_placement_constraints=1.09%
[2022-06-27 15:10:05,866]   nvme: average=0.01%, median=0.01%, without_placement_constraints=0.11%
[2022-06-27 15:10:05,868]   ssd: average=44.91%, median=44.56%, without_placement_constraints=40.89%
[2022-06-27 15:10:05,870]   hdd: average=98.72%, median=61.03%, without_placement_constraints=54.26%
[2022-06-27 15:10:05,870]   smr: average=0.00%, median=0.00%, without_placement_constraints=0.03%
[2022-06-27 15:10:05,877] cluster variance for crushclasses:
[2022-06-27 15:10:05,877]   mddu: 0.000
[2022-06-27 15:10:05,877]   mddm: 0.000
[2022-06-27 15:10:05,877]   nvme: 0.000
[2022-06-27 15:10:05,877]   ssd: 7.102
[2022-06-27 15:10:05,877]   hdd: 4505.848
[2022-06-27 15:10:05,877]   smr: 0.000
[2022-06-27 15:10:05,877] min osd.253 0.000%
[2022-06-27 15:10:05,877] max osd.1986 405.902%
[2022-06-27 15:10:05,877] osd.2231 has calculated usage >= 100%: 100.29076207793798%
[2022-06-27 15:10:05,878] osd.365 has calculated usage >= 100%: 100.55524411861991%
...
[2022-06-27 15:10:06,411] osd.2215 has calculated usage >= 100%: 341.60815893352543%
[2022-06-27 15:10:06,411] osd.2221 has calculated usage >= 100%: 342.0460392118455%
Traceback (most recent call last):
  File "./placementoptimizer.py", line 2079, in <module>
    try_pg_move.prepare_crush_check()
  File "./placementoptimizer.py", line 1007, in prepare_crush_check
    raise Exception(f"no trace found for {pg_osd} in {rule_root_name}")
Exception: no trace found for 2147483647 in default~hdd
```

**Comment by TheJJ** [comment]
please also try the latest version for this.
i don't understand how this error can occur, since that would be the "up" mapping of osds, and the up set should never have missing osds?
