### ISSUE TITLE
Balancer fails with crush rule combining 1SSD+2HDD

### ISSUE THREAD

**Issue by eriklindahl** [TheJJ/ceph-balancer#19]
Hi JJ!

FIrst, thanks for an AWESOME balancer! I'm in shock-and-awe how good, efficient and simple this is - it has achieved a virtually perfect balance on our system with a lots of mixed HDD sizes and nodes :-)

However, in addition to our large-storage volumes we also have a partition where we use 3-fold replication on 1SSD combined with 2HDDs. At least for our (relatively read-intensive) setup this works great in combination with NVMe DB/WAL devices for the HDDs. We get close to pure SSD performance on writes, and exactly the same read performance as a pure SSD array - but at 1/3 of the cost.

But... the JJbalancer fails for this pool. I have started to debug, and it seems to be caused by traces in prepare_crush_check where the code likely assumes all OSDs in the crush rule are the same class?

I will keep working on it, but I suspect there might be a close-to-trivial work-around to continue when OSDs have the wrong class, so I figured I should submit an issue if it's a 5-minute fix for somebody who knows the code better.

Here's the error with a bit of debug context; osd.277 is class ssd, osd.218 and osd.37 class hdd.

```
[2022-11-10 18:35:29,334] TRY-0 moving pg 5.3c1 (36/58) with 78.3G from osd.37
[2022-11-10 18:35:29,335]   OK => taking pg 5.3c1 from source osd.37 since it has too many of pool=5 (13 > 11.98997752947604)
[2022-11-10 18:35:29,335] prepare crush check for pg 5.3c1 currently up=[277, 218, 37]
[2022-11-10 18:35:29,335] rule:
{'name': '1ssd_2hdd',
 'steps': [{'item': -52, 'item_name': 'default~ssd', 'op': 'take'},
           {'num': 1, 'op': 'chooseleaf_firstn', 'type': 'host'},
           {'op': 'emit'},
           {'item': -24, 'item_name': 'default~hdd', 'op': 'take'},
           {'num': -1, 'op': 'chooseleaf_firstn', 'type': 'host'},
           {'op': 'emit'}]}
[2022-11-10 18:35:29,335] allowed reuses per rule step, starting at root: [2, 2, 2, 2, 1, 1]
[2022-11-10 18:35:29,336] processing crush step {'op': 'take', 'item': -52, 'item_name': 'default~ssd'} with tree_depth=0, rule_depth=0, item_uses=defaultdict(<class 'dict'>, {})
[2022-11-10 18:35:29,336]    trace for  277: [{'id': -52, 'type_name': 'root'}, {'id': -77, 'type_name': 'host'}, {'id': 277, 'type_name': 'osd'}]
[2022-11-10 18:35:29,336]    trace for  218: None
Traceback (most recent call last):
  File "./placementoptimizer.py", line 2081, in <module>
    try_pg_move.prepare_crush_check()
  File "./placementoptimizer.py", line 1009, in prepare_crush_check
    raise Exception(f"no trace found for {pg_osd} in {rule_root_name}")
Exception: no trace found for 218 in default~ssd
```

**Comment by TheJJ** [comment]
interesting use-case, thanks. it's a bit tricky supporting this properly, and there's a todo already in the code:
```
        # TODO: figure out the crush root for the old_osd, and use it for new_osd too
        # for now, just assume there's only one root per rule...
```

no promise when i can fix it, but it's more work than it looks i fear.

**Comment by TheJJ** [comment]
Ok, I've implemented it in af947ab4f868cb433fb2c0c9267d92e7e564889f, please try again :)
if there are sill problems, please notify me and send a state dump so i can easily reproduce and try with your cluster state.

**Comment by eriklindahl** [comment]
First, thanks a *bunch* for looking into this so quickly - I'm traveling this week, but was planning to gradually try and learn to solve and contribute it myself :-)

The latest version appears to be a clear step forward - the SSD balancing now works fine (when limiting it to that device class), but for HDDs I'm instead getting an error about multiple emits not being supported :-)

```
[2022-11-13 21:05:13,543] TRY-0 moving pg 35.51 (58/58) with 47.8G from osd.37
[2022-11-13 21:05:13,543]   OK => taking pg 35.51 from source osd.37 since it has too many of pool=35 (1 > 0.8279597158383636)
[2022-11-13 21:05:13,543] prepare crush check for pg 35.51 currently up=[187, 37, 413]
[2022-11-13 21:05:13,543] rule:
{'name': '1ssd_2hdd',
 'steps': [{'item': -52, 'item_name': 'default~ssd', 'op': 'take'},
           {'num': 1, 'op': 'chooseleaf_firstn', 'type': 'host'},
           {'op': 'emit'},
           {'item': -24, 'item_name': 'default~hdd', 'op': 'take'},
           {'num': -1, 'op': 'chooseleaf_firstn', 'type': 'host'},
           {'op': 'emit'}]}
[2022-11-13 21:05:13,544] allowed reuses per rule step, starting at root: [2, 2, 2, 2, 1, 1]
[2022-11-13 21:05:13,544] processing crush step {'op': 'take', 'item': -52, 'item_name': 'default~ssd'} with tree_depth=0, rule_depth=0, item_uses=defaultdict(<class 'dict'>, {})
[2022-11-13 21:05:13,544]    trace for  187: [{'id': -52, 'type_name': 'root'}, {'id': -87, 'type_name': 'host'}, {'id': 187, 'type_name': 'osd'}]
[2022-11-13 21:05:13,544] processing crush step {'op': 'chooseleaf_firstn', 'num': 1, 'type': 'host'} with tree_depth=0, rule_depth=1, item_uses=defaultdict(<class 'dict'>, {0: {-52: 1}})
[2022-11-13 21:05:13,544] processing crush step {'op': 'emit'} with tree_depth=1, rule_depth=2, item_uses=defaultdict(<class 'dict'>, {0: {-52: 1}, 1: {-87: 1}})
[2022-11-13 21:05:13,544] processing crush step {'op': 'take', 'item': -24, 'item_name': 'default~hdd'} with tree_depth=2, rule_depth=3, item_uses=defaultdict(<class 'dict'>, {0: {-52: 1}, 1: {-87: 1}, 2: {187: 1}, 3: {}, 4: {}, 5: {}})
[2022-11-13 21:05:13,544]    trace for   37: [{'id': -24, 'type_name': 'root'}, {'id': -2, 'type_name': 'host'}, {'id': 37, 'type_name': 'osd'}]
[2022-11-13 21:05:13,544]    trace for  413: [{'id': -24, 'type_name': 'root'}, {'id': -18, 'type_name': 'host'}, {'id': 413, 'type_name': 'osd'}]
[2022-11-13 21:05:13,544] processing crush step {'op': 'chooseleaf_firstn', 'num': -1, 'type': 'host'} with tree_depth=0, rule_depth=4, item_uses=defaultdict(<class 'dict'>, {0: {-52: 1}, 1: {-87: 1}, 2: {187: 1}, 3: {-24: 2}, 4: {}, 5: {}})
[2022-11-13 21:05:13,544] processing crush step {'op': 'emit'} with tree_depth=1, rule_depth=5, item_uses=defaultdict(<class 'dict'>, {0: {-52: 1}, 1: {-87: 1}, 2: {187: 1}, 3: {-24: 2}, 4: {-2: 1, -18: 1}, 5: {}})
Traceback (most recent call last):
  File "./placementoptimizer.py", line 2109, in <module>
    try_pg_move.prepare_crush_check()
  File "./placementoptimizer.py", line 1089, in prepare_crush_check
    raise Exception("multiple emits in crush rule not yet supported")
Exception: multiple emits in crush rule not yet supported
```

... and I'll also upload the state file.

**Comment by eriklindahl** [comment]
[https://www.dropbox.com/s/a6a09gc33cb2t46/cluster_state](cluster_state)

**Comment by eriklindahl** [comment]
PS: Of course I realise it might not be realistic to cover every single possible case, but perhaps this too can be simplified but still cover virtually all practical cases if one e.g. only considers emits for a particular device class when the balancer has been restricted to that class.

**Comment by TheJJ** [comment]
Ok, now multi-emit support is implemented. WIthout your state file, this would not have been possible, thanks!

Please try again :D

**Comment by TheJJ** [comment]
great! yes, if you see that its failing because it tries bad things, please tell me. I'l go ahead and close this then, feel free to open new issues or if that one here is still not fixed I'll of course reopen.

**Comment by TheJJ** [comment]
Maybe I can also try to spot mistakes - can you send me the invocation you're executing? And what your intended balance might look like (since I don't know your cluster topology and plan well :)
