### ISSUE TITLE
Crush topoloy exception

### ISSUE THREAD

**Issue by reedacus25** [TheJJ/ceph-balancer#21]
Having an issue where the script dies during a balance run.
```
$ python3 ./jj-balancer.py -v balance --max-pg-moves 10 | tee /tmp/balance-upmaps
[2023-01-10 10:20:34,509] gathering cluster state via ceph api...
[2023-01-10 10:20:40,984] running pg balancer
[2023-01-10 10:20:41,011] current OSD fill rate per crushclasses:
[2023-01-10 10:20:41,012]   hdd: average=60.71%, median=60.40%, crushclass_usage=75.52%
[2023-01-10 10:20:41,012]   ssd: average=58.43%, median=58.23%, crushclass_usage=62.43%
[2023-01-10 10:20:41,013] cluster variance for crushclasses:
[2023-01-10 10:20:41,013]   hdd: 3.238
[2023-01-10 10:20:41,013]   ssd: 9.636
[2023-01-10 10:20:41,013] min osd.53 52.013%
[2023-01-10 10:20:41,013] max osd.85 66.192%
[2023-01-10 10:20:41,022]   SAVE move 40.a9 osd.85 => osd.298
[2023-01-10 10:20:41,023]     props: size=35.5G remapped=False upmaps=0
[2023-01-10 10:20:41,023]     => variance new=3.1273334935204544 < 3.237997993456637=old
[2023-01-10 10:20:41,023]     new min osd.53 52.013%
[2023-01-10 10:20:41,023]         max osd.232 65.897%
[2023-01-10 10:20:41,023]     new cluster variance:
[2023-01-10 10:20:41,023]       hdd: 3.127
[2023-01-10 10:20:41,023]       ssd: 9.636
Traceback (most recent call last):
  File "./jj-balancer.py", line 2166, in <module>
    try_pg_move.prepare_crush_check()
  File "./jj-balancer.py", line 1098, in prepare_crush_check
    raise Exception(f"could not find item type {choose_type} "
Exception: could not find item type chassis requested by rule step {'op': 'chooseleaf_firstn', 'num': -1, 'type': 'chassis'}
```

I am assuming that it is due to a slightly non-standard crush topology/ruleset.
I have an hdd-root where the crush topology is root -> rack -> chassis -> host -> osd; then I have an ssd-root where the topology is root -> rack -> host -> osd (no chassis).

This is due to having some 8T hosts with 3x8T disks (2 per chassis, so 1 chassis = ~48T), some 8T hosts with 6x8T disks (1 per chassis), and some 24x2T hosts (1 per chassis), so that all of the chassis are ~48T and my crush rulesets take from chassis rather than host.

The SSD rulesets use host instead of chassis.
But I also have some "hybrid" rulesets where I take 1 from ssd-host, and take -1 from hdd-chassis.

So I'm guessing that this is why it is breaking on the `{'op': 'chooseleaf_firstn', 'num': -1, 'type': 'chassis'}`.

Let me know if there is anything I can provide to help.
Attaching a tree view of the host topology to hopefully visualize more easily.
This was pulled from `30f09f0` and the file is just renamed to `jj-balancer.py` for reasons.
Python is 3.8.10.

```
├── ROOT-hdd
│   └── RACK-rack-hdd
│       ├── CHASSIS-ceph-hdd-2t-01
│       │   └── HOST-ceph-hdd-2t-01
│       ├── CHASSIS-ceph-hdd-2t-02
│       │   └── HOST-ceph-hdd-2t-02
│       ├── CHASSIS-ceph-hdd-2t-03
│       │   └── HOST-ceph-hdd-2t-03
│       ├── CHASSIS-ceph-hdd-2t-04
│       │   └── HOST-ceph-hdd-2t-04
│       ├── CHASSIS-ceph-hdd-2t-05
│       │   └── HOST-ceph-hdd-2t-05
│       ├── CHASSIS-ceph-hdd-2t-06
│       │   └── HOST-ceph-hdd-2t-06
│       ├── CHASSIS-ceph-hdd-2t-07
│       │   └── HOST-ceph-hdd-2t-07
│       ├── CHASSIS-ceph-hdd-2t-08
│       │   └── HOST-ceph-hdd-2t-08
│       ├── CHASSIS-ceph-hdd-8t-0102
│       │   ├── HOST-ceph-hdd-8t-01
│       │   └── HOST-ceph-hdd-8t-02
│       ├── CHASSIS-ceph-hdd-8t-0304
│       │   ├── HOST-ceph-hdd-8t-03
│       │   └── HOST-ceph-hdd-8t-04
│       ├── CHASSIS-ceph-hdd-8t-0506
│       │   ├── HOST-ceph-hdd-8t-05
│       │   └── HOST-ceph-hdd-8t-06
│       ├── CHASSIS-ceph-hdd-8t-0708
│       │   ├── HOST-ceph-hdd-8t-07
│       │   └── HOST-ceph-hdd-8t-08
│       └── CHASSIS-ceph-hdd-8t-09
│           └── HOST-ceph-hdd-8t-09
└── ROOT-ssd
    └── RACK-rack-ssd
        ├── HOST-ceph-ssd-01
        ├── HOST-ceph-ssd-02
        ├── HOST-ceph-ssd-03
        ├── HOST-ceph-ssd-04
        ├── HOST-ceph-ssd-05
        └── HOST-ceph-ssd-06
```

**Comment by reedacus25** [comment]
Bit more context, if I exclude or target a "hybrid" ruleset pool with `--only-pool`, it reliably dies with the same error when targeting a hybrid pool, and reliably doesn't die when I exclude the hybrid pool(s).

So I do think that that is the culprit here.
Dump of the hybrid ruleset below.

```json
{
    "rule_id": 2,
    "rule_name": "hybrid_ruleset",
    "ruleset": 2,
    "type": 1,
    "min_size": 1,
    "max_size": 10,
    "steps": [
        {
            "op": "take",
            "item": -13,
            "item_name": "ssd"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 1,
            "type": "host"
        },
        {
            "op": "emit"
        },
        {
            "op": "take",
            "item": -1,
            "item_name": "hdd"
        },
        {
            "op": "chooseleaf_firstn",
            "num": -1,
            "type": "chassis"
        },
        {
            "op": "emit"
        }
    ]
}
```

**Comment by TheJJ** [comment]
hmm, I can't see an obvious reason.
can you send me your state dump file please? (preferrably upload it somewhere and send me the link to `jj at sft dawt lol`) then i can reproduce your invocation locally and try to figure it out.
