### ISSUE TITLE
Fatal error in get_osd_candidates

### ISSUE THREAD

**Issue by jermudgeon** [TheJJ/ceph-balancer#23]
```
./placementoptimizer.py -v balance
[2023-01-26 08:42:54,343] gathering cluster state via ceph api...
[2023-01-26 08:43:06,262] running pg balancer
[2023-01-26 08:43:06,267] current OSD fill rate per crushclasses:
[2023-01-26 08:43:06,268]   hdd: average=66.15%, median=60.57%, crushclass_usage=64.46%
[2023-01-26 08:43:06,268] cluster variance for crushclasses:
[2023-01-26 08:43:06,269]   hdd: 284.034
[2023-01-26 08:43:06,269] min osd.2 56.273%
[2023-01-26 08:43:06,269] max osd.12 121.969%
[2023-01-26 08:43:06,269] osd.12 has calculated usage >= 100%: 121.9685%
[2023-01-26 08:43:06,270] osd.3 is source osd in pg <__main__.PGMoveChecker object at 0x7f2f9d773e20>
[2023-01-26 08:43:06,270] self.pg_osds is [7, 13, 10, 12, 1, 6]
Traceback (most recent call last):
  File "/root/install/ceph-balancer/./placementoptimizer.py", line 2138, in <module>
    pool_pg_count_ideal = pg_mappings.pool_pg_count_ideal(pg_pool, try_pg_move.get_osd_candidates(osd_from))
  File "/root/install/ceph-balancer/./placementoptimizer.py", line 890, in get_osd_candidates
    root_name = self.root_names[pg_osd_idx]
IndexError: list index out of range
```

I added a little bit of debugging to determine that osd_from is not in pg_osd_idx

         ```
    186 active+clean
             30  active+remapped+backfilling
             4   active+clean+scrubbing+deep
             4   active+remapped+backfill_toofull
             1   active+clean+scrubbing
```

Is the remapped+backfill_toofull state breaking this? What additional debug output should I try?

**Comment by TheJJ** [comment]
can you create a state dump and upload it somewhere, and send me the link to jj at sft dawt lol please? then i can easily reproduce and hopefully fix the bug :)

**Comment by jermudgeon** [comment]
Sure Jonas; which commands do you need the output from? (I'm not familiar with 'state dump' as a discrete set.)

**Comment by TheJJ** [comment]
It's `./placementoptimizer.py -v gather /tmp/lolfile.xz` :smiley_cat:

**Comment by jermudgeon** [comment]
It was small, so sent as attachment. LMK if it doesn't make it and I'll upload it somewheres. Thanks for looking at it!

**Comment by TheJJ** [comment]
this is now fixed, but there seem to be not many movement options for your cluster. the best I could get now is `17.14T` for `cephfs425`, but the usage differences are within 2% now :)
