### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by dvanders** [TheJJ/ceph-balancer#3]
Getting a ZeroDivisionError when we run the balance command

```
# ./placementoptimizer.py -v balance --max-pg-moves 10
[2021-11-13 16:42:46,885] running pg balancer
Traceback (most recent call last):
  File "./placementoptimizer.py", line 1745, in <module>
    pg_mappings = PGMappings(pgs, osds)
  File "./placementoptimizer.py", line 1225, in __init__
    pg_obj_size = shardsize / pg_objs
ZeroDivisionError: division by zero
```

I'm guessing it's because we have a couple osds down with zero PGs?

```
# ceph osd df | sort -k17 | head
ID   CLASS WEIGHT   REWEIGHT SIZE    RAW USE DATA     OMAP    META    AVAIL    %USE  VAR  PGS STATUS 
MIN/MAX VAR: 0.07/1.28  STDDEV: 17.89
                       TOTAL 8.7 PiB 6.0 PiB  5.9 PiB 986 GiB  21 TiB  2.8 PiB 68.37                 
1073   hdd 12.87889        0     0 B     0 B      0 B     0 B     0 B      0 B     0    0   0   down 
  71   hdd 12.87889        0     0 B     0 B      0 B     0 B     0 B      0 B     0    0   0   down 
1050   hdd 12.87889  1.00000  13 TiB 1.4 TiB  1.1 TiB  52 KiB 3.8 GiB   12 TiB 10.77 0.16   9     up 
1054   hdd 12.87889  1.00000  13 TiB 1.4 TiB  1.1 TiB 132 KiB 3.9 GiB   12 TiB 10.98 0.16   7     up 
1063   hdd 12.87889  1.00000  13 TiB 1.6 TiB  1.4 TiB  52 KiB 4.6 GiB   11 TiB 12.64 0.18  10     up 
```

**Comment by TheJJ** [comment]
Hi Dan, thanks for the report!
I think I've fixed it in 7482eca9748ec7228de61abebcc2170d6587dc21. I haven't encountered this since none of my clusters has pgs with 0 objects in them :)
