### ISSUE TITLE
./placementoptimizer.py showremapped balks at cluster topology changes

### ISSUE THREAD

**Issue by patrakov** [TheJJ/ceph-balancer#33]
```
# ./placementoptimizer.py showremapped
Traceback (most recent call last):
  File "/root/./placementoptimizer.py", line 5403, in <module>
    exit(main())
  File "/root/./placementoptimizer.py", line 5358, in main
    state = ClusterState(args.state, osdsize_method=osdsize_method)
  File "/root/./placementoptimizer.py", line 720, in __init__
    self.load(statefile)
  File "/root/./placementoptimizer.py", line 768, in load
    raise RuntimeError("Cluster topology changed during information gathering (e.g. a pg changed state). "
RuntimeError: Cluster topology changed during information gathering (e.g. a pg changed state). Wait for things to calm down and try again
```

Surely this precaution against cluster topology changes does not make sense for read-only and purely informational subcommands such as `showremapped`?

**Comment by TheJJ** [comment]
unfortunately it does, since we collect the cluster information the same way for generating movements or showing infos. And the current way calls multiple commands and checks if the osdmap changed and thus things are likely inconsistent.

I planned on adding a secondary collection mode that uses the osdmap only, which should work atomically then. Would you be willing to send me your cluster's state dump and osdmap file so I have a sample for such a pair in addition to my cluster?
 If so, please use `ceph osd getmap -o osdmapfile` and shortly after `./placementoptimizer gather state.xz` so they are for the same osdmap epoch, then please upload/send them to me to jj -at- sft.lol :)

**Comment by patrakov** [comment]
I do not have such permission from the owner of this cluster, sorry.

In any case, retrying the command has helped.

**Comment by TheJJ** [comment]
alright, no problem!
