### ISSUE TITLE
variance requires at least two data points

### ISSUE THREAD

**Issue by TheGeka** [TheJJ/ceph-balancer#7]
The script just throws an error

- ceph version 16.2.7 (f9aa029788115b5df5eeee328f584156565ee5b7) pacific (stable)
- Python 3.9.2
- Script version: latest

Output:
```
./placementoptimizer.py -v balance --max-pg-moves 10 | tee /tmp/balance-upmaps
[2022-03-17 15:29:12,622] gathering cluster state via ceph api...
[2022-03-17 15:29:15,735] running pg balancer
[2022-03-17 15:29:15,737] current OSD fill rate per crushclasses:
[2022-03-17 15:29:15,738]   hdd: average=121.93%, median=107.85%, without_placement_constraints=64.31%
[2022-03-17 15:29:15,738]   ssd: average=47.30%, median=47.30%, without_placement_constraints=44.71%
Traceback (most recent call last):
  File "/root/ceph-balancer/./placementoptimizer.py", line 1945, in <module>
    init_cluster_variance = get_cluster_variance(enabled_crushclasses, pg_mappings)
  File "/root/ceph-balancer/./placementoptimizer.py", line 1870, in get_cluster_variance
    class_variance = statistics.variance(osd_usages)
  File "/usr/lib/python3.9/statistics.py", line 739, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points
```

**Comment by TheJJ** [comment]
interesting, didn't know that :) i've fixed this in f13bd2cb818820603e3825fbb0a2827473d97691

How many osds do you have in this crushclass? how i see it it would only crash there if there's either 0 or 1 osds in the crushclass.

If you have 0, we have to investigate where we should skip the crushclass if there's no member in there.

**Comment by TheGeka** [comment]
Just tried and it worked with any issue, i only have 1 osd in the ssd crushclass at the moment.

**Comment by TheJJ** [comment]
great!
